version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: zero-start
    path: ""
    text-resources:
      - path: src/lang/*.json
        format: flat-key-value
